pull_request_rules:
  - name: merge pull requests from dependabot if CI passes
    conditions:
    - author=dependabot[bot]
    - status-success=ci/circleci
    actions:
      merge:
        method: merge