# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.20-browsers
        environment:
          TZ: Asia/Tokyo
          CHROME_BIN: "/usr/bin/google-chrome"
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: |
          sudo apt install libappindicator3-1
          sudo apt install libgbm1
          curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb
          sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
          rm google-chrome.deb
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Flow Types
          # https://discuss.circleci.com/t/circleci-terminal-is-a-tty-but-term-is-not-set/9965/8
          command: TERM=dumb yarn flow
      - run:
          name: TS Types
          command: yarn test:types
      - run:
          name: Test Coverage
          command: yarn test:cover
      - run:
          name: Unittests
          command: yarn test:unit:ci
      - run:
          name: E2E Tests
          command: yarn test:e2e
